<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="$(BasePath)\src\Eto\sdk\Sdk.props" />

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Tutorial3</RootNamespace>
    <Name>Tutorial3 - Table Layout</Name>
    <MacBundleDotNet>False</MacBundleDotNet>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Program.fs" />
  </ItemGroup>

  <Import Project="$(BasePath)\src\Eto\sdk\Sdk.targets" />

</Project>