#!/bin/sh

# modify these to your app's name and executable,
# then place your exe and dll's in the Resources folder

APP_NAME="MyApp"
ASSEMBLY="MyApp.exe"


# Determine app name and locations

MACOS_DIR=$(cd "$(dirname "$0")"; pwd)
APP_ROOT=${MACOS_DIR%%/Contents/MacOS}
 
CONTENTS_DIR="$APP_ROOT/Contents"
RESOURCES_PATH="$CONTENTS_DIR/Resources"

MONO_FRAMEWORK_PATH=/Library/Frameworks/Mono.framework/Versions/Current

#Environment setup
export DYLD_FALLBACK_LIBRARY_PATH="$MONO_FRAMEWORK_PATH/lib:$DYLD_FALLBACK_LIBRARY_PATH:$(HOME)/lib:/usr/local/lib:/lib:/usr/lib"
export PATH="$MONO_FRAMEWORK_PATH/bin:$PATH"
export DYLD_LIBRARY_PATH="$RESOURCES_PATH:$DYLD_LIBRARY_PATH"

# Check Mono is installed and has correct version
"$MACOS_DIR/mono-version-check" "$APP_NAME" 2 8 || exit 1

# Pass the executable name as the last parameter of MONO_ENV_OPTIONS
# since some NSApplication APIs will poke at the startup arguments and do not
# like the .exe there
export MONO_ENV_OPTIONS="$MONO_OPTIONS $RESOURCES_PATH/$ASSEMBLY"

#run the app
if [ ! -f "$APP_ROOT/mono" ]; then 
	ln -s "$MONO_FRAMEWORK_PATH/bin/mono" "$APP_ROOT/mono" 
fi
exec "$APP_ROOT/mono"
